# CoreDocument - Applicazione Gestione Documenti
# Usa i servizi condivisi da CoreServices

services:
  # Backend API (NestJS)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: coredocument-backend
    restart: unless-stopped
    environment:
      # Database - usa il MySQL condiviso
      DATABASE_URL: mysql://${MYSQL_USER:-coredocument}:${MYSQL_PASSWORD:-password}@mysql:3306/${MYSQL_DATABASE:-coredocument}

      # JWT
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-this}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}

      # MinIO - usa il MinIO condiviso
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      MINIO_BUCKET_NAME: coredocument-files

      # Meilisearch - usa il Meilisearch condiviso
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_API_KEY: ${MEILI_MASTER_KEY:-masterKeyChangeThis}

      # App
      APP_PORT: 3002
      APP_URL: ${APP_URL:-http://localhost}
      NODE_ENV: production
    ports:
      - "3002:3002"
    networks:
      - core-network  # Usa la network condivisa
    command: sh -c "npx prisma migrate deploy || true && node dist/main"

  # Frontend (Next.js)
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:81/api}
    container_name: coredocument-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:81/api}
      NODE_ENV: production
    ports:
      - "3003:3000"
    depends_on:
      - backend
    networks:
      - core-network  # Usa la network condivisa

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: coredocument-nginx
    restart: unless-stopped
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - core-network  # Usa la network condivisa

# Usa la network esterna creata da CoreServices
networks:
  core-network:
    external: true
    name: core-network
